# -- MYSQL
SELECT QUARTER, COUNT(A.ID) AS ECOLI_COUNT
FROM ECOLI_DATA A
JOIN (
    SELECT ID,
           CASE WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN '1Q'
           WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN '2Q'
           WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN '3Q'
           ELSE '4Q' END AS QUARTER
    FROM ECOLI_DATA
    ) AS B
ON A.ID = B.ID
GROUP BY QUARTER
ORDER BY QUARTER;
           
