-- MYSQL
SELECT TREE.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_TREE TREE
JOIN ITEM_INFO INFO ON TREE.ITEM_ID =  INFO.ITEM_ID
WHERE PARENT_ITEM_ID IN 
    (SELECT ITEM_ID
     FROM ITEM_INFO
     WHERE RARITY = 'RARE')
ORDER BY TREE.ITEM_ID DESC;